In [1]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
# Importing the dataset
df = pd.read_csv('D:/Data Science/Data-Science-main/pmf.csv')

In [7]:
df.head()

AREA  RAINFALL  AVG_TEMPERATURE  HUMIDITY  GROUND_WATERLEVEL  PRODUCTION
0  108608      8.18             24.1      64.0               4.71      376544
1  141154    166.00             26.4      74.3               5.86      429108
2  103207     10.98             24.1      60.1               6.07      332223
3  133365    137.04             28.0      73.0               5.67      345015
4   48545      7.30             24.6      64.0               6.47      152965

In [8]:
print(df.dtypes)

AREA                   int64
RAINFALL             float64
AVG_TEMPERATURE      float64
HUMIDITY             float64
GROUND_WATERLEVEL    float64
PRODUCTION             int64
dtype: object


In [9]:
df['AREA'] = df['AREA'].astype(float) 
df['PRODUCTION'] = df['PRODUCTION'].astype(float) 
  
print()

In [10]:
print(df.dtypes)

AREA                 float64
RAINFALL             float64
AVG_TEMPERATURE      float64
HUMIDITY             float64
GROUND_WATERLEVEL    float64
PRODUCTION           float64
dtype: object


In [11]:
df

AREA  RAINFALL  AVG_TEMPERATURE  HUMIDITY  GROUND_WATERLEVEL  \
0   108608.0      8.18             24.1      64.0              4.710   
1   141154.0    166.00             26.4      74.3              5.860   
2   103207.0     10.98             24.1      60.1              6.070   
3   133365.0    137.04             28.0      73.0              5.670   
4    48545.0      7.30             24.6      64.0              6.470   
5   122858.0    179.24             29.4      71.0              6.100   
6    64718.0     14.85             23.9      62.1              6.630   
7    65453.0    107.94             27.9      69.6              8.330   
8    18182.0     14.85             23.8      65.2             10.140   
9   146979.0    204.94             26.3      72.5              8.860   
10  119417.0     13.68             24.8      59.8              5.960   
11  166750.0    178.16             27.1      74.0              5.130   
12  166759.0      7.94             24.1      63.8              4.420   
13  130000.0    164.18             26.3      71.2              2.450   
14  152000.0     28.28             24.5      64.3              2.700   
15  160406.0    175.80             26.0      71.0              2.418   
16  175551.0      2.50             24.1      65.3              3.022   
17   84886.0    123.14             25.0      72.0              3.390   
18   77439.0      9.58             24.6      64.6              3.980   
19  159548.0    235.82             28.8      74.0              2.580   
20  221971.0     12.86             24.6      63.0              2.592   
21  185727.0    139.84             28.4      77.0              2.840   
22  157649.0      9.83             24.9      59.0              3.650   

    PRODUCTION  
0     376544.0  
1     429108.0  
2     332223.0  
3     345015.0  
4     152965.0  
5     395726.0  
6     206321.0  
7     147989.0  
8      50382.0  
9     501639.0  
10    410675.0  
11    521094.0  
12    548470.0  
13    441000.0  
14    545000.0  
15    543135.0  
16    632861.0  
17    274182.0  
18    239209.0  
19    523465.0  
20    828396.0  
21    601858.0  
22    518192.0

In [12]:
X = df.values
print(X.shape)
print(X)

(23, 6)
[[1.08608e+05 8.18000e+00 2.41000e+01 6.40000e+01 4.71000e+00 3.76544e+05]
 [1.41154e+05 1.66000e+02 2.64000e+01 7.43000e+01 5.86000e+00 4.29108e+05]
 [1.03207e+05 1.09800e+01 2.41000e+01 6.01000e+01 6.07000e+00 3.32223e+05]
 [1.33365e+05 1.37040e+02 2.80000e+01 7.30000e+01 5.67000e+00 3.45015e+05]
 [4.85450e+04 7.30000e+00 2.46000e+01 6.40000e+01 6.47000e+00 1.52965e+05]
 [1.22858e+05 1.79240e+02 2.94000e+01 7.10000e+01 6.10000e+00 3.95726e+05]
 [6.47180e+04 1.48500e+01 2.39000e+01 6.21000e+01 6.63000e+00 2.06321e+05]
 [6.54530e+04 1.07940e+02 2.79000e+01 6.96000e+01 8.33000e+00 1.47989e+05]
 [1.81820e+04 1.48500e+01 2.38000e+01 6.52000e+01 1.01400e+01 5.03820e+04]
 [1.46979e+05 2.04940e+02 2.63000e+01 7.25000e+01 8.86000e+00 5.01639e+05]
 [1.19417e+05 1.36800e+01 2.48000e+01 5.98000e+01 5.96000e+00 4.10675e+05]
 [1.66750e+05 1.78160e+02 2.71000e+01 7.40000e+01 5.13000e+00 5.21094e+05]
 [1.66759e+05 7.94000e+00 2.41000e+01 6.38000e+01 4.42000e+00 5.48470e+05]
 [1.30000e+05 1.6

In [13]:
y = X[:,-1]
X = X[:,:5]

In [14]:
print(X.shape)
print(y.shape)
print(X)
print(y)

(23, 5)
(23,)
[[1.08608e+05 8.18000e+00 2.41000e+01 6.40000e+01 4.71000e+00]
 [1.41154e+05 1.66000e+02 2.64000e+01 7.43000e+01 5.86000e+00]
 [1.03207e+05 1.09800e+01 2.41000e+01 6.01000e+01 6.07000e+00]
 [1.33365e+05 1.37040e+02 2.80000e+01 7.30000e+01 5.67000e+00]
 [4.85450e+04 7.30000e+00 2.46000e+01 6.40000e+01 6.47000e+00]
 [1.22858e+05 1.79240e+02 2.94000e+01 7.10000e+01 6.10000e+00]
 [6.47180e+04 1.48500e+01 2.39000e+01 6.21000e+01 6.63000e+00]
 [6.54530e+04 1.07940e+02 2.79000e+01 6.96000e+01 8.33000e+00]
 [1.81820e+04 1.48500e+01 2.38000e+01 6.52000e+01 1.01400e+01]
 [1.46979e+05 2.04940e+02 2.63000e+01 7.25000e+01 8.86000e+00]
 [1.19417e+05 1.36800e+01 2.48000e+01 5.98000e+01 5.96000e+00]
 [1.66750e+05 1.78160e+02 2.71000e+01 7.40000e+01 5.13000e+00]
 [1.66759e+05 7.94000e+00 2.41000e+01 6.38000e+01 4.42000e+00]
 [1.30000e+05 1.64180e+02 2.63000e+01 7.12000e+01 2.45000e+00]
 [1.52000e+05 2.82800e+01 2.45000e+01 6.43000e+01 2.70000e+00]
 [1.60406e+05 1.75800e+02 2.60000e+01 7.1

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [21]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
print(y_pred)
print()

[536476.07810264 399635.50657711 560618.45581484 514086.8730177
 752605.31012601]


In [23]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
print(score)

0.9083154010188321
